### ISSUE TITLE
Observing TDMA Schedule miss-configuration 

### ISSUE THREAD

**Issue by petergeorge1** [adjacentlink/emane#101]
In experimentation, if a TDMA schedule is created incorrectly where two nodes can potentially transmit into the same slot number towards a single destination, i can observe the slot contention though traffic testing but cannot see any drop errors highlighted in the stat tables indicating a problem. Are my observations correct?

Thanks

**Comment by sgalgano** [comment]
At the receiver you will see an indication of this condition as bytes dropped due to `Slot Error` in the `{Broad,Uni}castByteDropTable[0,3]` table(s). Then consulting the `RxSlotStatusTable` for a breakdown of slot errors, you will see `Lock` errors.
