### ISSUE TITLE
Build Issue with protobuf shared library

### ISSUE THREAD

**Issue by jrejwdr** [adjacentlink/emane#104]
I tried to build EMANE, as wiki instructions, Ubuntu 14.04/16.04 LTS.
 I got the following error 
  debian/rules override_dh_makeshlibs
make[2]: Entering directory '/home/jwdr/emane/.debbuild/emane-1.2.4'
dh_listpackages | xargs -I {} dpkg-gensymbols -Pdebian/{} -p{} -q
make[2]: Leaving directory '/home/jwdr/emane/.debbuild/emane-1.2.4'
   dh_shlibdeps
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libprotobuf.so.17 (used by debian/emane-libs/usr/lib/libemane.so)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/emane-libs.substvars debian/emane-libs/usr/lib/libemanexmlparser.so debian/emane-libs/usr/lib/libemane.so returned exit code 2
debian/rules:49: recipe for target 'binary' failed
make[1]: *** [binary] Error 2
make[1]: Leaving directory '/home/jwdr/emane/.debbuild/emane-1.2.4'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Makefile:892: recipe for target 'deb' failed
make: *** [deb] Error 2

I check /usr/local/lib/libprotobuf.so.17, it referenced softlink libprotobuf.so.17.0.0
please help

**Comment by sgalgano** [comment]
It appears that you are using a locally built/installed protocol buffers: ` /usr/local/lib/libprotobuf.so.17`. Note the */usr/local*.

From the [build instructions](https://github.com/adjacentlink/emane/wiki/Build#ubuntu-14041604-lts) you should install: `libprotobuf-dev`.
