### ISSUE TITLE
Is this the correct mailing list?

### ISSUE THREAD

**Issue by WorksWellWithOthers** [adjacentlink/emane#105]
Join the EMANE mailing list and post a question:

**https://publists.nrl.navy.mil/mailman/listinfo/emane-users**

**Comment by sgalgano** [comment]
Unfortunately that mailing list is no longer active. It was not managed by Adjacent Link and the hosting organization no longer hosts mailing lists.

We use [gitflow](https://nvie.com/posts/a-successful-git-branching-model) branch management for emane. The emane *master* branch represents the latest release.  Current emane development can be found on the *develop* branch, which has an updated [README]( https://github.com/adjacentlink/emane/commit/306f08b80fdde5db290a808c4a997476cc363a35) no longer referencing the list.
