### ISSUE TITLE
TDMA Slot Types

### ISSUE THREAD

**Issue by petergeorge1** [adjacentlink/emane#107]
Hi, just a general question on the TDMA Model. Can this be configured or are you aware of any EMANE work on trying to achieve a contention-based TDMA slot? Thanks.

**Comment by patelkb** [comment]
The TDMA model utilizes a policy class template to define the schedule.
 The open source model utilizes an event scheduler policy where events
are used to define the Tx/Rx schedule for each node.  The schedule can
be update in real-time by an external process via events.

You can use the open source TDMA model with the policy based class
template and replace the event scheduler with your own contention based
TDMA slot scheduler.

kb

Kaushik B. Patel
Adjacent Link LLC
