### ISSUE TITLE
TDMA BW parameter question

### ISSUE THREAD

**Issue by petergeorge1** [adjacentlink/emane#108]
Hi,

When instantiating a TDMA model, your examples include a 'bandwidth' parameter for the physical layer definition. However, as part of the TDMA schedule specification, you also specify 'bandwidth' as part of any full schedule's structure specification. Can you clarify why this parameter is needed as part of the physical layer definition?

Thanks
Peter.

**Comment by sgalgano** [comment]
Internally the TDMA radio model uses a control message to set the emulator physical layer instance receive frequencies (frequencies of interest) and the transceiver bandwidth based on a received schedule.  Any physical layer configuration for these parameters is overwritten by the corresponding control message value.
