### ISSUE TITLE
Fading model and passloss in PHY Layer

### ISSUE THREAD

**Issue by ChengDaHaI** [adjacentlink/emane#118]
Hi,
 I have two question about the PHY layer parameters.

1. In the [wiki](https://github.com/adjacentlink/emane/wiki/Physical-Layer-Model#fadingmodel), it says the fading model can be set to event. However, in the five events:

> -  Antenna Profile Event
> - Comm Effect Event
> - Location Event
> - Pathloss Event
> - TDMA Schedule Event

i don't find any one related with fading.

2. In the [wiki](https://github.com/adjacentlink/emane/wiki/Physical-Layer-Model#propagationmodel), it says the propagation model  (or pathloss) can be precomputed(pathloss event) or freespace/v2ray (based on gps location). However, i found that even though it is set as precomputed and pathloss event is given, the link between nodes (viewed via olsrd) could be affected by gps location. Does that make sense?

Thank you!

**Comment by sgalgano** [comment]
The documentation is lacking in that area. I added the missing references for the Fading Selection Event and the  syntax for sending the event via the [EEL Generator](https://github.com/adjacentlink/emane/wiki/EEL-Generator). You can also use `emaneevent-fadingselection` to send one-shot events via the command line. Fading model support came in with commit 559ef4228aed56c37cf6ef91e42131b3c7094f74.

If positions are known, propagation delay is used by the spectrum monitor when determining start of reception (SoR) time.
