### ISSUE TITLE
Best Practices for Custom Shim Building on CentOS

### ISSUE THREAD

**Issue by hideogump** [adjacentlink/emane#123]
I am building a custom shim under CentOS 7 and have observed a few issues that I did not have under Ubuntu.

Previously, to use the EMANE build system, I simply duplicated much of what was done for the Comm Effect shim based on the autotools build process, customized it, and then performed the standard autogen.sh, configure, make, make deb (or rpm) sequence.   Prior to this I made a few small changes to configure.ac, and makefile.am in the shims folder to include my custom shim.

Under CentOS, when I perform a "make install" in either my custom shim (or the CommEffects shim), the destination for the libraries is /usr/local/lib.  This differs from the library path in the formal .rpms (generated either from source or through the official RPM distribution), which is /usr/lib64.

Despite explicitly setting my $PATH and $LD_LIBRARY_PATH to include /usr/local/lib, EMANE fails to load the custom shim library.

I also noticed that the custom shim itself has an absolute path reference to the EMANE shared library (usr/lib64/libemane.so) rather through the standard path (see below).  This seems like an RPATH issue in the build process where it should be set to NULL.

Is there a preferred method for building custom shims for EMANE under CentOS that I am perhaps missing?  Are there changes necessary to other files to allow the 'make rpm' process work for additional custom content?

COMM EFFECT SHIM

[user@localhost .libs]$ ldd libcommeffectshim.so
	linux-vdso.so.1 =>  (0x00007ffec7be2000)
	**libemane.so => /home/user/emane/emane-1.2.4/src/libemane/.libs/libemane.so** (0x00007f3044fba000)

CUSTOM SHIM

[user@localhost .libs]$ ldd libcustomphyshim.so
    linux-vdso.so.1 =>  (0x00007ffee1ead000)
    ****libemane.so => /home/user/emane/emane-1.2.3/src/libemane/.libs/libemane.so**** (0x00007f650d07c000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007f650ce78000)
    librt.so.1 => /lib64/librt.so.1 (0x00007f650cc70000)

**Comment by sgalgano** [comment]
Setting `LD_LIBRARY_PATH` to include the directories containing your libraries is a [typical](https://github.com/sgalgano/environments-foss) way to load emane components out of git repos when doing developer level testing. 

If you want to `make install` to a standard system location use:

```
$ ./configure --prefix=/usr
```

If you want to install to a non-standard location you should look at adding a file to `/etc/ld.so.conf.d/`  and running `ldconfig`.

For a standalone RPM spec example take a look at [emane-model-lte.spec.in](https://github.com/adjacentlink/emane-model-lte/blob/master/emane-model-lte.spec.in).

**Comment by hideogump** [comment]
Thanks
