### ISSUE TITLE
Install emane on high performance computer without root privilege 

### ISSUE THREAD

**Issue by ChengDaHaI** [adjacentlink/emane#131]
In the Wiki, the building and installing both need root to execute sudo/yum command. Is there an instruction about how to build or install the pre-built packets without root?

P.S. This is the first step if someone wants to emulate tens or hundreds of nodes on a server or cluster.

**Comment by sgalgano** [comment]
Provided the required dependencies are installed, you can [build](https://github.com/adjacentlink/emane/wiki/Build#general-build-instructions) and install emane to a location (`./configure --prefix /alt/install/location`) accessible to a specific user.
