### ISSUE TITLE
Raw frames in EMANE

### ISSUE THREAD

**Issue by carelphillipkruger** [adjacentlink/emane#133]
Hi,

I would like to send a raw 802.15.4 physical layer frame through emane. Do I have to write a custom shim / transport or is it possible to send the data frame using the raw transport ?.

**Comment by sgalgano** [comment]
You will probably need to write a new transport. The raw transport still operates on ethernet frames.

**Comment by carelphillipkruger** [comment]
Tnks for the reply . After looking at the raw transport code I realised that it uses packet capture to suck in all visible ethernet frames into EMANE. I thus have to create a new transport as suggested.
