### ISSUE TITLE
Question about phased array

### ISSUE THREAD

**Issue by WorksWellWithOthers** [adjacentlink/emane#149]
Good time of day!

Does emane simulate a phased array?

**Comment by patelkb** [comment]
EMANE currently supports directional antenna.  If your design only
requires the use of a single array at any given time, this should be
sufficient.

A new feature is in the works that will support MIMO.  Assuming your
phased array antenna is simultaneously using multiple arrays, you will
need the new MIMO feature.  The new feature will be available in 2020.
Exact release date is still TBD.

Regardless, you will have to develop your own radio model that uses the
EMANE framework antenna features to support your phased array
implementation.

kb


Kaushik B. Patel
Adjacent Link LLC
