### ISSUE TITLE
Best way to retrieve RX Power in Python

### ISSUE THREAD

**Issue by WorksWellWithOthers** [adjacentlink/emane#151]
What would be the recommended way to retrieve RX Power data in Python?

I'm tempted to grab the data from emane shell using the subprocess. 
This is what I tried so far, 

```
import emane.shell as es  
test = es.EMANEShell('host',port)  
test.do_get('table nems mac')
```

**Comment by WorksWellWithOthers** [comment]
es.EMANEShell('node-1',47000)

**Comment by WorksWellWithOthers** [comment]
I would like to store the retrieved values in a variable. Something like,

`data = test.do_get('table nems mac')`

**Comment by sgalgano** [comment]
Take a look at the control port [tutorial](https://github.com/adjacentlink/emane-control-port-tutorial/wiki/Statistic-Table-Query).

**Comment by WorksWellWithOthers** [comment]
Thank you!
