### ISSUE TITLE
Does the offset set by the <placement> element account for the change in the Platform's heading?

### ISSUE THREAD

**Issue by WorksWellWithOthers** [adjacentlink/emane#170]
If I set an offset to be "10" North in the <placement> element.  
Would that radio always be "10" apart from the default "0" position, even when the NEM platforms are moved and the heading is changed? 
I'm trying to make sure it doesn't reset back to 0 after I move the platform. 

If it does stay "10" apart does it adjust with the heading changes? 
So if the platform is no longer facing North and is now facing East, the offset would be "10" East.

Can I use negative numbers as well? i.e. "-10" north?

**Comment by patelkb** [comment]
The antenna placement information persists and defines a fixed location
of the antenna on the platform relative to the platform's longitudinal,
latitudinal and vertical axes.

Kaushik B. Patel
Adjacent Link LLC
