### ISSUE TITLE
How was the antenna pattern rendered on the wiki?

### ISSUE THREAD

**Issue by WorksWellWithOthers** [adjacentlink/emane#176]
How was this image of the antenna pattern rendered on this page (tool name)?

[Antenna Profile](https://github.com/adjacentlink/emane/wiki/Antenna-Profile)

**Comment by sgalgano** [comment]
Those images were generated with an internal tool that is no longer in use. 

Take a look at [emane-antenna-simple-viewer](https://github.com/sgalgano/emane-antenna-simple-viewer). This is a very simple rendering tool we sometimes use during training class. Might be a good starting point for adapting to your needs.
