### ISSUE TITLE
The script emane/scripts/emanegentransportxml may need to decode the xml before writing xml to a file

### ISSUE THREAD

**Issue by zihefang** [adjacentlink/emane#178]
## Environment:
    Ubuntu 18.04
    emane-tutorial 0.27
    emane 1.2.6
    python 3.6.9
    

## Issue
 According to [emane-tutorial/wiki/Demonstration-2](https://github.com/adjacentlink/emane-tutorial/wiki/Demonstration-2), when I execute this command `chmod u+w transportdaemon?.xml && emanegentransportxml -v platform*.xml` in emane-tutorial/2, it will generate some transportdaemon?.xml files with somthing similar to the following content:

```

b'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<!DOCTYPE transportdaemon SYSTEM "file:///usr/share/emane/dtd/transportdaemon.dtd">\n<transportdaemon>\n  <instance nemid="1">\n    <param name="platformendpoint" value="10.99.0.100:8201"/>\n    <param name="transportendpoint" value="10.99.0.1:8301"/>\n    <transport definition="transvirtual.xml">\n      <param name="address" value="10.100.0.1"/>\n      <param name="mask" value="255.255.255.0"/>\n    </transport>\n  </instance>\n</transportdaemon>\n'

```
Files in this format will lead to failing to parse document in transportdaemon?.xml. The details are as follows：
![图片](https://user-images.githubusercontent.com/26756325/92594469-65513c80-f2d5-11ea-8a46-e2edfc9a1a14.png)

## solution
Just change line 293 `print(xml, file=output)` to `print(xml.decode('UTF-8'), file=output)` to solve this problem.
After that, the transportdaemon?.xml files will be normal and be parsed normally.

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE transportdaemon SYSTEM "file:///usr/share/emane/dtd/transportdaemon.dtd">
<transportdaemon>
  <instance nemid="1">
    <param name="platformendpoint" value="10.99.0.100:8201"/>
    <param name="transportendpoint" value="10.99.0.1:8301"/>
    <transport definition="transvirtual.xml">
      <param name="address" value="10.100.0.1"/>
      <param name="mask" value="255.255.255.0"/>
    </transport>
  </instance>
</transportdaemon>
```

**Comment by sgalgano** [comment]
Thanks for reporting the issue and debugging.
