### ISSUE TITLE
Core GUI nodes not moving after issuing Emane Location events

### ISSUE THREAD

**Issue by lbressler** [adjacentlink/emane#199]
I'm not sure if this is a Core or Emane issue.
I am currently using Core 6.1.0 and Emane 1.2.5 on Ubuntu 18.04.

In earlier versions of Core and Emane, I could issue location events, which caused the nodes to move in the Core GUI.
If I issue the following sample event in a node's terminal:
  emaneevent-location-3 1 latitude=45 longitude=-120 altitude=4000 
I can see the new location in the emanesh LocationEventInfoTable. But the node does not move on the screen.

Is there some special Core or Emane config setting that I need?

Thanks.

Larry Bressler

**Comment by sgalgano** [comment]
This is a core issue. Please direct your question to the core project.
