### ISSUE TITLE
Setting up different precomputed pathloss on different operating frequencies of the same waveform 

### ISSUE THREAD

**Issue by kmanousakis** [adjacentlink/emane#206]
Is there a way to set different precomputed pathloss on the same nemID when this nemID corresponds to a waveform that operates on multiple different frequencies? For example pathloss X freq F1 and pathloss X+K dB freq F2. Is there a utility that supports that and if not how can I achieve that?

**Comment by sgalgano** [comment]
That capability is not presently supported. You'd have to modify the physical layer and event processing to allow for specifying per frequency pathloss values (or modifiers).
