### ISSUE TITLE
make: *** No rule to make target 'rpm'.  Stop.

### ISSUE THREAD

**Issue by andredemori** [adjacentlink/emane#207]
Hello, I am facing this issue during the installation process. I'm using Ubuntu 20.04.

Build
=====

`./autogen.sh && ./configure && make`

For information on configuration options see:

#./configure --help

Install
=======

`make install`

Build RPMs
==========

`make rpm`

`make: *** No rule to make target 'rpm'.  Stop.`

I didn't find any .rpm file

**Comment by eschreiber-alink** [comment]
You'll want to build debs on Ubuntu. "make deb" instead of "make rpm". See:

https://github.com/adjacentlink/emane/wiki/Build#ubuntu-2004-lts
