### ISSUE TITLE
Understanding PHY layer calculations

### ISSUE THREAD

**Issue by vivianchiong** [adjacentlink/emane#230]
Hello,

Isn't the rxSensitivity calculated [here](https://github.com/adjacentlink/emane/wiki/Physical-Layer-Model#receive-power-calculation) technically noise floor?

If we want rxSensitivity, the calculation is missing a term ebN0 -- i.e. we should be discarding the packet if the rxPower is less than the sum of (−174 + noiseFigure + 10log(bandWidth)) + some ebN0 term (e.g. 4 dB).

Is there an error in my understanding?

Thank you so much!

**Comment by sgalgano** [comment]
The Rx Sensitivity calculation in the emulator physical layer is used as a threshold to determine the lowest receive power for a signal to be detected.  If that threshold is met, the frame is passed up to the radio model to determine, based on its specific receive logic, if the frame is properly received.   Adding an C/N term (i.e. ebNo) implies a determination of the minimum receive power necessary to achieve a minimum level of completion confidence associated with the C/N term.

**Comment by vivianchiong** [comment]
Thank you!
