### ISSUE TITLE
Meaning of noisemode wrt different radio models

### ISSUE THREAD

**Issue by vivianchiong** [adjacentlink/emane#233]
When I had `noisemode` set to `all` for IEEE 802.11abg radio model, I got an error running the scenario that said I can only use `none` and `outofband` for the IEEE 802.11abg model.

Why is this the case? What exactly is `noisemode` configuring for different radio models?

I don't come from an RF background so I apologize if this question is out of scope. Please let me know if there is a wiki page or link that would help give some background on this parameter instead.

Thank you so much!

**Comment by sgalgano** [comment]
`noisemode` controls how the physical layer records the receive energy of over-the-air frames. Radio models have different degrees of complexity and mechanisms for handling in-band noise. In emane, the term in-band is used to refer to spectrum energy from the same waveform and out-of-band (`outofband`) refers to energy from different waveforms. The IEEE 802.11abg radio model uses a statistical model for in-band noise, so the physical layer is configured to only track energy (noise) from other waveforms (out-of-band). Setting `noisemode` to `none` disables noise processing in the physical layer.
