### ISSUE TITLE
Queue latency reset in queuemetricmanager.cc not working properly

### ISSUE THREAD

**Issue by williamsu2** [adjacentlink/emane#25]
The reset logic in getQueueMetrics() around line 155 of queuemetricmanager.cc does not seem to reset the stat.   This caused the runnig average to be incorrect.  This is in EMANE code /src/libemane/ queuemetricmanager.cc.  I replaced the lines

           iter.second.u32NumDiscards_ = 0;
           iter.second.delayMicroseconds_ = EMANE::Microseconds::zero();

with

          QueueData & rData = getQueueData_i(iter.first);
          rData.u32NumSamples_ = 0;
          rData.u32NumDiscards_ = 0;
          rData.delayMicroseconds_ = EMANE::Microseconds::zero();

This quick workaround seems to do the trick.

**Comment by jgiovatto** [comment]
williamsu2,
Can you verify the feature/issuse25 branch fixes the issue you reported and leave feedback on the pull request: https://github.com/adjacentlink/emane/pull/28
Thanks
