### ISSUE TITLE
Tutorial 0 - level 0 fails

### ISSUE THREAD

**Issue by lesliemulder** [adjacentlink/emane#43]
In trying to run the tutorial 0 level 0 I get the following responses:

root@cedardrome:/home/m/emane-tutorial/0# ls
bypassmac.xml     eventservice.xml           NO-node-gpsd
bypassnem.xml     gpsdlocationagent1.xml     NO-node-routing
bypassphy.xml     gpsdlocationagent2.xml     persist
demo-start        Makefile                   platform1.xml
demo-stop         NO-host-emaneeventservice  platform2.xml
eelgenerator.xml  NO-node-emane              routing1.conf
eventdaemon1.xml  NO-node-emaneeventd        routing2.conf
eventdaemon2.xml  NO-node-emanetransportd    transvirtual.xml

root@cedardrome:/home/m/emane-tutorial/0# ./demo-start
Creating bridge: emanenode0
kernel.sched_rt_runtime_us = -1
Starting lxc instance: node-1
Starting lxc instance: node-2
root@cedardrome:/home/m/emane-tutorial/0#

The demo-start script terminates immedaitely.

The log file for node 1 is 

    lxc-execute 1450896658.716 ERROR    lxc_sync - sync.c:__sync_wake:62 - sync wake failure : Broken pipe
    lxc-execute 1450896658.716 ERROR    lxc_start - start.c:__lxc_start:1121 - failed to spawn 'node-1'

The log file for node 2 is the same, excepting that it notes node-2  not node-1

**Comment by sgalgano** [comment]
Wrong project. See https://github.com/adjacentlink/emane-tutorial.
