### ISSUE TITLE
Problem with leading zero on certain radio frequency values

### ISSUE THREAD

**Issue by bebopagogo** [adjacentlink/emane#45]
When providing radio transmit frequency or frequency of interest parameter values for a certain range of values (e..g 0.8G, 0.9G), EMANE does not accept the configuration.  If the leading zero is omitted (e.g., using ".9G" instead of "0.9G"), EMANE accepts the configuration and works properly.

**Comment by sgalgano** [comment]
The issue occurs when using floating point representation with K, M or G SI unit values for integer configuration items such as frequency. The conversion code applies the appropriate power of 10 but does not remove any leading zeros that may result. 

After conversion, a leading 0 causes the result to be treated as an octal value. If the parameter value only contains values in the set of allowable octal characters, the conversion would succeed but as base 8.  If the value contains digits outside the octal set (e.g. 0.9G), conversion would fail with an unallowed character exception description.

Functionality can be added to remove any leading zeros after SI unit application, being mindful of possible sign inclusion. This will effectively cause all integer values with SI units to be treated as base 10, which is probably the most logical expectation.
