### ISSUE TITLE
Unused member variable

### ISSUE THREAD

**Issue by tomgoff** [adjacentlink/emane#70]
The `dAltitudeRadians`_ member variable of `EMANE::Position` is unused (and uninitialized) and can probably be removed.

Removing it would avoid some uninitialized warnings.

The attached patch is a possible fix.
[position.h.patch.txt](https://github.com/adjacentlink/emane/files/578629/position.h.patch.txt)

**Comment by sgalgano** [comment]
Agreed that it should eventually be removed but I don't think removing it now is a good idea. Doing so would change the size of `EMANE::Position` and break ABI. To remove the compiler warning we could just initialize it to 0.

**Comment by tomgoff** [comment]
Initializing to 0 sounds good to me.
