### ISSUE TITLE
Improved epoll_wait() error handling

### ISSUE THREAD

**Issue by tomgoff** [adjacentlink/emane#71]
`EMANE::NEMQueuedLayer::processWorkQueue` should probably continue when `epoll_wait()` returns an error due to being interrupted by a signal handler.

The attached patch is a possible fix.
[nemqueuedlayer.cc.patch.txt](https://github.com/adjacentlink/emane/files/578652/nemqueuedlayer.cc.patch.txt)

**Comment by sgalgano** [comment]
Thanks for the patch.
