### ISSUE TITLE
Building from source throws error regarding protoc version

### ISSUE THREAD

**Issue by kjacks21** [adjacentlink/emane#72]
I am on step 3 of the [installation instructions](https://github.com/adjacentlink/emane/wiki/Build#Ubuntu%2014.04/16.04%20LTS) for Ubuntu 16.04 and am getting an error regarding my protoc version. Below is the portion where the error is thrown. I checked `antennaprofileevent.pb.h` and it said protoc version 3, but that is what I have. You can see that I check the protoc version at the end. Any suggestions?

make[3]: Entering directory '/home/kyle/Documents/gmuGRA/EMANE/emane/src/libemane'
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -std=c++11 -DPACKAGE_NAME=\"emane\" -DPACKAGE_TARNAME=\"emane\" -DPACKAGE_VERSION=\"1.0.1\" -DPACKAGE_STRING=\"emane\ 1.0.1\" -DPACKAGE_BUGREPORT=\"emane\ at\ adjacent\ link\ dot\ com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"emane\" -DVERSION=\"1.0.1\" -DHAVE_CXX11=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -D__BYTE_ORDER=__LITTLE_ENDIAN -D__LITTLE_ENDIAN=1234 -D__BIG_ENDIAN=4321 -I.  -I../../include  -I/usr/include/libxml2 -pthread  -I/usr/include/uuid -DVERBOSE_LOGGING  -g -O3 -Wall -Wextra -MT libemane_la-antennaprofileevent.lo -MD -MP -MF .deps/libemane_la-antennaprofileevent.Tpo -c -o libemane_la-antennaprofileevent.lo `test -f 'antennaprofileevent.cc' || echo './'`antennaprofileevent.cc
libtool: compile:  g++ -std=c++11 -DPACKAGE_NAME=\"emane\" -DPACKAGE_TARNAME=\"emane\" -DPACKAGE_VERSION=\"1.0.1\" "-DPACKAGE_STRING=\"emane 1.0.1\"" "-DPACKAGE_BUGREPORT=\"emane at adjacent link dot com\"" -DPACKAGE_URL=\"\" -DPACKAGE=\"emane\" -DVERSION=\"1.0.1\" -DHAVE_CXX11=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -D__BYTE_ORDER=__LITTLE_ENDIAN -D__LITTLE_ENDIAN=1234 -D__BIG_ENDIAN=4321 -I. -I../../include -I/usr/include/libxml2 -pthread -I/usr/include/uuid -DVERBOSE_LOGGING -g -O3 -Wall -Wextra -MT libemane_la-antennaprofileevent.lo -MD -MP -MF .deps/libemane_la-antennaprofileevent.Tpo -c antennaprofileevent.cc  -fPIC -DPIC -o .libs/libemane_la-antennaprofileevent.o
In file included from antennaprofileevent.cc:35:0:
antennaprofileevent.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
antennaprofileevent.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
antennaprofileevent.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
antennaprofileevent.pb.h:22:35: fatal error: google/protobuf/arena.h: No such file or directory
compilation terminated.
Makefile:1094: recipe for target 'libemane_la-antennaprofileevent.lo' failed
make[3]: *** [libemane_la-antennaprofileevent.lo] Error 1
make[3]: Leaving directory '/home/kyle/Documents/gmuGRA/EMANE/emane/src/libemane'
Makefile:2240: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/home/kyle/Documents/gmuGRA/EMANE/emane/src/libemane'
Makefile:397: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/kyle/Documents/gmuGRA/EMANE/emane/src'
Makefile:444: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
(python2) kyle@kyle-ThinkPad-T450s:~/Documents/gmuGRA/EMANE/emane$ protoc --version
libprotoc 3.0.0

**Comment by sgalgano** [comment]
On my Ubuntu 16.04 build system I have the following packages installed:

```
# dpkg -l | grep protobuf
ii  libprotobuf-dev:amd64                 2.6.1-1.3                                     amd64        protocol buffers C++ library (development files)
ii  libprotobuf-lite9v5:amd64             2.6.1-1.3                                     amd64        protocol buffers C++ library (lite version)
ii  libprotobuf9v5:amd64                  2.6.1-1.3                                     amd64        protocol buffers C++ library
ii  protobuf-compiler                     2.6.1-1.3                                     amd64        compiler for protocol buffer definition files
ii  python-protobuf                       2.6.1-1.3                                     amd64        Python bindings for protocol buffers
```

I don't have an issue building. The same is true when using  a base 16.04 docker image and the previously referenced instructions. Note: emane uses proto2.

It looks like you may have a mismatch between protoc and the installed development headers.

This line looks suspect:

```
antennaprofileevent.pb.h:22:35: fatal error: google/protobuf/arena.h: No such file or directory
compilation terminated.
```

**Comment by kjacks21** [comment]
Thank you.
