### ISSUE TITLE
libemane Headers Not Intalled

### ISSUE THREAD

**Issue by joeclarkia** [adjacentlink/emane#76]
When I install EMANE, I see that libemane.so is installed and appears to have symbols matching the source code.  However, the libemane headers are not installed (eventservice.h, multicastsocket.h, for example).  Why is this?  I want to write C++ code using libemane classes but am not sure how to do this without the headers.

**Comment by sgalgano** [comment]
Only the headers that are part of the API for building models, transports and event components are installed via `make install` (rpm devel and deb dev).

API headers live in the toplevel  source include directory. Changes to API classes (headers) are made only when necessary and usually as part of a larger effort that modifies emulator capabilities at the cost of breaking ABI for existing binary plugins.

Internal headers, those found within the toplevel src directory, can change at any time and are not intended for external use.
