### ISSUE TITLE
Cannot find autoconf when building

### ISSUE THREAD

**Issue by emirljuca** [adjacentlink/emane#93]
When running ./autogen.sh I get the following...

I am using Ubuntu 18.04
```
user@ubuntu:~/Downloads/emane$ ./autogen.sh
./autogen.sh: line 82: autoreconf: command not found
```

**Comment by sgalgano** [comment]
https://github.com/adjacentlink/emane/wiki/Build#ubuntu-1804-lts

**Comment by emirljuca** [comment]
Ahh I see, okay thanks! Was following from introduction, maybe put the build and install at the top of the wiki? Up to you.
