### ISSUE TITLE
question about gpsd location events and velocity

### ISSUE THREAD

**Issue by ed-silvus** [adjacentlink/emane#94]
Is publishing a new LocationEvent the only way to update a node's gps coordinates? I noticed that specifying an azimuth, elevation, and magnitude does not update the latitude and longitude. 

For example (using tutorial vm) if i do,

event = LocationEvent()
event.append(1,latitude=40.021235,longitude=-74.317441,altitude=3.0,azimuth=90.0,elevation=0.0,magnitude=20.0)
service.publish(1,event)

and then look at the pseudoterminalfile (/dev/pts/0) 

then i get:

$GPGGA,172631,4001.2740,N,07419.0464,W,2,08,1.1,3.0,M,-34.0,M,,*7B
$GPRMC,172631,A,4001.2740,N,07419.0464,W,000.0,000.0,200319,000.0,W*76
$GPGSA,A,3,01,02,03,04,05,06,07,08,,,,,1.8,1.1,1.3*31
$GPGSV,2,1,08,01,41,104,41,03,09,084,51,05,70,030,39,07,35,185,25*75
$GPGSV,2,2,08,05,10,297,25,07,53,311,21,09,02,029,29,11,48,064,32*7B
$GPVTG,90.0,T,90.0,M,38.9,N,72.0,K*49
$GPGGA,172632,4001.2740,N,07419.0464,W,2,08,1.1,3.0,M,-34.0,M,,*78
$GPRMC,172632,A,4001.2740,N,07419.0464,W,000.0,000.0,200319,000.0,W*75
$GPGSA,A,3,01,02,03,04,05,06,07,08,,,,,1.8,1.1,1.3*31
$GPGSV,2,1,08,01,41,104,41,03,09,084,51,05,70,030,39,07,35,185,25*75
$GPGSV,2,2,08,05,10,297,25,07,53,311,21,09,02,029,29,11,48,064,32*7B
$GPVTG,90.0,T,90.0,M,38.9,N,72.0,K*49

thanks,
Ed

**Comment by sgalgano** [comment]
Only location events update position. Velocity information is used only for directional antenna calculations.
