### ISSUE TITLE
dynamic mcs index

### ISSUE THREAD

**Issue by ed-silvus** [adjacentlink/emane#95]
I would like to have the mcs index change dynamically according to the sinr. Is there a suggested way to modify the ieee80211 model in order to achieve this?

**Comment by sgalgano** [comment]
The complexity of the modification depends on your exact experiment goals. If you want to implement a feature with per destination MCS indexes, it will be more complex than if you just change it for all unicast and broadcast traffic. Both would require closed loop SINR info from receiver to transmitter to make changes at the transmitter.

**Comment by ed-silvus** [comment]
I would like to change the unicast rate per destination. Is the getMessageDurationMicroseconds function the correct area of the code to look at?

**Comment by sgalgano** [comment]
Yes
