### ISSUE TITLE
Multiple NEMs in a single emulator or One NEM per emulator

### ISSUE THREAD

**Issue by wtswzyw** [adjacentlink/emane#99]
I find that _demo 2_ in the emane-tutorial initializes all the NEMs in a single emulator and has the OTA channel disabled. So, can I say there are two basic ways to run a wireless network simulation? A Multiple NEMs in a single emulator without a OTA channel or One NEM per emulator  with a OTA channel?
And, could you please explain whether these two ways have different influence on the simulation performance? If they do, how do I choose a appropriate one?

**Comment by sgalgano** [comment]
It is almost never a good idea to instantiate more than one NEM in an emulator instance. 

The emulator does not use lock-free data structures. Performance of any non-trivial emulation will run with better fidelity using one NEM per emulator instance - and depending on the radio model, assigning specific CPUs to those emulator instances.
